version: "3"

services:
  mysql:
    image: mysql:5.7
    # connects local db to my sql container
    # volumes:
    #   - ./db:/docker-entrypoint-initdb.d
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: wordpress
      MYSQL_DATABASE: wordpress
      MYSQL_user: wordpress
      MYSQL_PASSWORD: wordpress

  wordpress:
    image: wordpress
    depends_on:
      - mysql
    # volumes:
    #   - ./src:/var/www/html
    links:
      - mysql:mysql
    ports:
      - 8080:80
    restart: always
    environment:
      WORDPRESS_DB_PASSWORD: wordpress
